defaults: &defaults
  uri: <%= ENV['MONGOLAB_URI'] %>

development:
  <<: *defaults
  database: foodsquares_development

test:
  <<: *defaults
  database: foodsquares_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>