defaults: &defaults
  uri: <%= ENV['MONGOLAB_URI'] %>

development:
  <<: *defaults
  #host: 127.0.0.1
  #port: 27017
  #database: foodsquares_development
  uri: <%= ENV['MONGOLAB_URI'] %>
  database: heroku_app3461086

test:
  <<: *defaults
  host: 127.0.0.1
  port: 27017
  database: foodsquares_test

# set these environment variables on your prod server
production:
  uri: <%= ENV['MONGOLAB_URI'] %>